### ISSUE TITLE
http://localhost/laradrop/containers NOT FOUND

### ISSUE THREAD

**Issue by minhliem86** [jasekz/laradrop#23] opened 2017-03-20 10:05 UTC
Hi Jasekz,

Thank for your package. It's interesting me. But I have a problem when install it into my project. When I install and run my url it show alert "Not Found". I followed all steps to install. Thank Jasekz again. Regards,

**Comment by jasekz** [comment] 2017-03-20 12:42
@minhliem86 Is your app located in a subdirectory, i.e http://localhost/myapp?  Also, please take a look at https://github.com/jasekz/laradrop/issues/16 to see if anything there may apply to your situation.

**Comment by minhliem86** [comment] 2017-03-24 00:16
Thanks jasekz so much.

**Comment by jasekz** [comment] 2017-03-27 16:33
@minhliem86 I'm going to close this out.  Feel free to reopen if the issue is not resolved.

**Closed as completed by jasekz** 2017-03-27 16:33 UTC
